language: php

php: [ 5.5, hhvm]

sudo: false

matrix:
    allow_failures:
        - php: hhvm
        
before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - bin/phpunit
